### ISSUE TITLE
How to run in a non development env

### ISSUE THREAD

**Issue by newmanw** [AstroDigital/libra#16]
Possible to provide instructions on how to configure server to run in a non development env?

Currently running:

``` bash
grunt connect:dist
```

However that still feels more like develop.

Is there a way you would recommend serving out this app in a production env?

**Comment by jflasher** [comment]
Hi @newmanw, we updated the README to have a section about [deployment](https://github.com/AstroDigital/libra/blob/develop/README.md#deploying-the-app). 

Basically you can run `grunt build` to create a `dist` directory and that can be served via any normal mechanism for serving files. We are currently using S3 to serve the production site.

**Comment by newmanw** [comment]
@jflasher thanks!  I did grab the dist and serve it out with apache once I realized it was just static page.  Great to know I am not missing anything.

BTW, beautiful app thanks so much.

**Comment by jflasher** [comment]
Thanks @newmanw, glad you like it!
