### ISSUE TITLE
Newer versions of angular-leafet-directive is not backwards compatible

### ISSUE THREAD

**Issue by newmanw** [AstroDigital/libra#17]
Current bower.json:

```
"angular-leaflet-directive": "^0.7.10",
```

Pull a newer version (ie just build now that a 0.8+ is available) and hover/click events on the map don't work.  Best I can tell that the object passed back via events no longer includes 'markerName', which looks to have changed to 'modelName'

I agree this is horrible versioning on the angular leaflet guys part as 0.8 is not a major versoin change and should not include backwards braking changes, but it is what it is.

**Comment by drewbo** [comment]
Good catch. I'll pin for now and look to update during the next refactor or feature addition. Not worried on the breaking change since it's pre-1.0; essentially anything goes until then.

**Comment by newmanw** [comment]
@drewbo great app, and thanks for the quick turnaround!
